// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlmY0dAmdiRpSi3Gos5JpdsOqT43SiI2k',
    appId: '1:591150554844:web:a9509a70941b3a69f09e19',
    messagingSenderId: '591150554844',
    projectId: 'askme-ask',
    authDomain: 'askme-ask.firebaseapp.com',
    storageBucket: 'askme-ask.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7foPzD8nf49A-wjrJyLb9lp6k4fIyKlg',
    appId: '1:591150554844:android:ed20bfeeac33570df09e19',
    messagingSenderId: '591150554844',
    projectId: 'askme-ask',
    storageBucket: 'askme-ask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHthzYEVAZqFpMHZzLeOMe3gb3dwW_R04',
    appId: '1:591150554844:ios:bf578411ed2e315bf09e19',
    messagingSenderId: '591150554844',
    projectId: 'askme-ask',
    storageBucket: 'askme-ask.appspot.com',
    iosClientId: '591150554844-l0ca41ks0ho1muattj2auq5u3dt7pqlv.apps.googleusercontent.com',
    iosBundleId: 'com.example.askme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHthzYEVAZqFpMHZzLeOMe3gb3dwW_R04',
    appId: '1:591150554844:ios:93e328f179939faaf09e19',
    messagingSenderId: '591150554844',
    projectId: 'askme-ask',
    storageBucket: 'askme-ask.appspot.com',
    iosClientId: '591150554844-157g4jjrmdi274n56uv7l6nqcedhaie3.apps.googleusercontent.com',
    iosBundleId: 'com.example.askme.RunnerTests',
  );
}
